//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationPoderosa.WSEmployeeService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmployeeContract", Namespace="http://schemas.datacontract.org/2004/07/WcfServicePoderosa.Contracts.Contracts")]
    [System.SerializableAttribute()]
    public partial class EmployeeContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorInformation", Namespace="http://schemas.datacontract.org/2004/07/WcfServicePoderosa.Contracts.Contracts")]
    [System.SerializableAttribute()]
    public partial class ErrorInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSEmployeeService.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/DoWork", ReplyAction="http://tempuri.org/IEmployeeService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/DoWork", ReplyAction="http://tempuri.org/IEmployeeService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAllEmployes", ReplyAction="http://tempuri.org/IEmployeeService/GetAllEmployesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebApplicationPoderosa.WSEmployeeService.ErrorInformation), Action="http://tempuri.org/IEmployeeService/GetAllEmployesErrorInformationFault", Name="ErrorInformation", Namespace="http://schemas.datacontract.org/2004/07/WcfServicePoderosa.Contracts.Contracts")]
        WebApplicationPoderosa.WSEmployeeService.EmployeeContract[] GetAllEmployes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAllEmployes", ReplyAction="http://tempuri.org/IEmployeeService/GetAllEmployesResponse")]
        System.Threading.Tasks.Task<WebApplicationPoderosa.WSEmployeeService.EmployeeContract[]> GetAllEmployesAsync();
        
        // CODEGEN: Generating message contract since the operation CreateEmployee is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/CreateEmployee", ReplyAction="http://tempuri.org/IEmployeeService/CreateEmployeeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebApplicationPoderosa.WSEmployeeService.ErrorInformation), Action="http://tempuri.org/IEmployeeService/CreateEmployeeErrorInformationFault", Name="ErrorInformation", Namespace="http://schemas.datacontract.org/2004/07/WcfServicePoderosa.Contracts.Contracts")]
        WebApplicationPoderosa.WSEmployeeService.CreateEmployeeResponse CreateEmployee(WebApplicationPoderosa.WSEmployeeService.EmployeeContract1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/CreateEmployee", ReplyAction="http://tempuri.org/IEmployeeService/CreateEmployeeResponse")]
        System.Threading.Tasks.Task<WebApplicationPoderosa.WSEmployeeService.CreateEmployeeResponse> CreateEmployeeAsync(WebApplicationPoderosa.WSEmployeeService.EmployeeContract1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EmployeeContract1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public string Name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Age;
        
        public EmployeeContract1() {
        }
        
        public EmployeeContract1(string Name, int Age) {
            this.Name = Name;
            this.Age = Age;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEmployeeResponse {
        
        public CreateEmployeeResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : WebApplicationPoderosa.WSEmployeeService.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<WebApplicationPoderosa.WSEmployeeService.IEmployeeService>, WebApplicationPoderosa.WSEmployeeService.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public WebApplicationPoderosa.WSEmployeeService.EmployeeContract[] GetAllEmployes() {
            return base.Channel.GetAllEmployes();
        }
        
        public System.Threading.Tasks.Task<WebApplicationPoderosa.WSEmployeeService.EmployeeContract[]> GetAllEmployesAsync() {
            return base.Channel.GetAllEmployesAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationPoderosa.WSEmployeeService.CreateEmployeeResponse WebApplicationPoderosa.WSEmployeeService.IEmployeeService.CreateEmployee(WebApplicationPoderosa.WSEmployeeService.EmployeeContract1 request) {
            return base.Channel.CreateEmployee(request);
        }
        
        public void CreateEmployee(string Name, int Age) {
            WebApplicationPoderosa.WSEmployeeService.EmployeeContract1 inValue = new WebApplicationPoderosa.WSEmployeeService.EmployeeContract1();
            inValue.Name = Name;
            inValue.Age = Age;
            WebApplicationPoderosa.WSEmployeeService.CreateEmployeeResponse retVal = ((WebApplicationPoderosa.WSEmployeeService.IEmployeeService)(this)).CreateEmployee(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationPoderosa.WSEmployeeService.CreateEmployeeResponse> WebApplicationPoderosa.WSEmployeeService.IEmployeeService.CreateEmployeeAsync(WebApplicationPoderosa.WSEmployeeService.EmployeeContract1 request) {
            return base.Channel.CreateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationPoderosa.WSEmployeeService.CreateEmployeeResponse> CreateEmployeeAsync(string Name, int Age) {
            WebApplicationPoderosa.WSEmployeeService.EmployeeContract1 inValue = new WebApplicationPoderosa.WSEmployeeService.EmployeeContract1();
            inValue.Name = Name;
            inValue.Age = Age;
            return ((WebApplicationPoderosa.WSEmployeeService.IEmployeeService)(this)).CreateEmployeeAsync(inValue);
        }
    }
}
